export const abandonwares = [
    {
        name: "A BEE C'S",
        year: '1983',
        platform: 'Commodore 64',
        releasedIn: 'United States',
        genre: 'Educational',
        theme: ['Arcade', 'Pre-school', 'Real-time'],
    },
    {
        name: 'B-17 FLYING FORTRESS',
        year: '1992',
        platform: 'DOS',
        releasedIn: 'United States',
        genre: 'Simulation',
        theme: [
            'Flight',
            ' Historical Battle',
            'Vehicular Combat Simulator',
            'World War II',
        ],
    },
    {
        name: 'D-BUG',
        year: '1983',
        platform: 'Commodore 64',
        releasedIn: 'United States',
        genre: 'Puzzle',
        theme: ['Mini-Games', 'Real-Time'],
    },
    {
        name: 'G-NETIX',
        year: '1995',
        platform: 'Windows 3.x',
        releasedIn: 'United States',
        genre: 'Simulation',
        theme: ['Health', 'Science'],
    },
    {
        name: 'S.C.A.R.S.',
        year: '1998',
        platform: 'Windows',
        releasedIn: 'Germany',
        genre: 'Driving',
        theme: [
            'Arcade',
            'Automobile',
            'Combat Vehicules',
            'Sci-Fi / Futuristic',
            'Shooter',
            'Track Racing',
            'Vehicle Simulator',
        ],
    },
]
