name: Pipeline

# Events
on:
    push:
        branches: [main, staging]
    pull_request:
        branches: [main, staging]
    workflow_dispatch:

# Steps
jobs:
    avoid_reduncy:
        runs-on: ubuntu-20.04
        permissions:
            actions: write
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.12.1
              with:
                  access_token: ${{ github.token }}

    lint:
        runs-on: ubuntu-20.04
        defaults:
          run:
            working-directory: ./frontend
        steps:
            - name: Checkout to last commit
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Format
              run: npm run format
            - name: Lint
              run: npm run lint
    build:
        needs: [avoid_reduncy, lint]
        runs-on: ubuntu-20.04
        defaults:
          run:
            working-directory: ./frontend
        env:
          NEXT_PUBLIC_PRIVY_ID: ${{ secrets.NEXT_PUBLIC_PRIVY_ID }}
        steps:
            - name: Checkout to last commit
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
